version: '3.3'

services:
  auth:
    restart: always
    # build:
    #   context: ..
    #   dockerfile: Dockerfile
    image: whatwewant/openresty-basic-auth
    ports:
      - 8080:80
      - 8090:8090
    environment:
      # PORT: 80
      # SERVER_NAME: localhost
      # CLIENT_MAX_BODY_SIZE: 1m 
      # PROXY_READ_TIMEOUT: 60s
      # WORKER_PROCESSES: auto
      BEARER_TOKEN: zero
      PROXY_PASS_UPSTREAM: web:8080

  web:
    image: nginx:1.17.2-alpine
    # ports:
    #   - 8080:8080
    volumes:
      - ./web/conf.d:/etc/nginx/conf.d
      - ./web/html:/var/www/html